@extends('layouts.main')

@section('content')

    <h1>Уголок</h1>

    <p align="justify">
        <strong>Уголок</strong> – один из <a href="/">самых распространенных видов металлопроката</a>. Представляет
        собой металлическую полосу, изогнутую вдоль длины, обычно под углом 90 градусов.</p>

    <div class="table-container-outer">
        <div class="table-container-fade"></div>
        <div class="table-container">
            <table border="1" width="100%">
                <caption>По способу производства и типу сечения уголки делятся:</caption>
                <tbody>
                <tr>
                    <th width="33%">ГОСТ</th>
                    <th width="33%">Вид сечения</th>
                    <th width="33%">Способ производства</th>
                </tr>
                <tr>

                    <td>ГОСТ 19771-93</td>
                    <td>Гнутый</td>
                    <td>Равнополочный</td>
                </tr>
                <tr>

                    <td>ГОСТ 19772-93</td>
                    <td>Гнутый</td>
                    <td>Неравнополочный</td>
                </tr>
                <tr>

                    <td>ГОСТ 8509-93</td>
                    <td>Горячекатаный</td>
                    <td>Равнополочный</td>
                </tr>
                <tr>

                    <td>ГОСТ 8510-86</td>
                    <td>Горячекатаный</td>
                    <td>Неравнополочный</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div><br>
    <p align="justify">
        Горячая <a href="/">прокатка металла</a> заключается в том, что будущий <strong>уголок</strong> - заготовку в
        виде слитка - прокатывают через вращающиеся валы, где под воздействием давления формуется уголок. Гнутый уголок
        получают на профилегибочных агрегатах.</p>

    <p align="justify">
        Чаще всего уголки изготавливаются из углеродистой стали обычного качества, но могут быть изготовлены из
        низколегированной стали повышенной прочности.</p>

    <img src="/img/ugolok/ugolok_gnutiy_neravnopolochniy.gif" alt="Уголок гнутый неравнополочный ГОСТ  19772-93">
    <img src="/img/ugolok/ugolok_gnutiy_ravnopolochniy.gif" alt="Уголок гнутый равнополочный ГОСТ  19771-93">
    <img src="/img/ugolok/ugolok_goriachekataniy_neravnopolochniy.gif"
         alt="Уголок горячекатанный неравнополочный ГОСТ  8510-86">
    <img src="/img/ugolok/ugolok_goriachekataniy_ravnopolochniy.gif"
         alt="Уголок горячекатанный равнополочный ГОСТ 8509-93">

    <p align="justify">
        Используют уголок в строительстве и при монтаже разнообразных конструкций. Не уступает уголок <a
                href="/">балке</a> и <a href="/">швеллеру</a> по техническим
        характеристикам, и наравне с ними, применяется для укрепления несущих перегородок, организации проемов, усиления
        конструкций. Применение уголка в некоторых случаях выгодней по экономическим показателям, и удобней в некоторых
        типах конструкций.</p>


    <p align="justify">
        <b>Толщина полок уголка</b> может быть разнообразной, от 3мм. Длинна - обычно от 3м до 12м. По согласованию с
        Заказчиком длина уголка может быть иной.</p>


    <p align="justify">
        В случае необходимости уголки могут покрываться разнообразными пленками, обеспечивающими защиту от коррозии и
        преждевременного разрушения. </p>


    <p align="justify">
        Основным покрытием считается оцинковка, которая часто применяется там, где требуются нержавеющие уголки, также
        отдельно изготавливаются уголки из нержавеющей стали. Нержавеющие уголки обычно используются на объектах с
        повышенной влажностью, а оцинкованные применяются в пищевой и медицинской промышленности. Важно, что только
        оцинковка уголка позволяет избежать окисления металла и сохранить его стерильность в случае необходимости.</p>

    <h2>Вес уголка стального горячекатаного равнополочного по ГОСТ 8509-93</h2>
    <div class="table-container-outer">
        <div class="table-container-fade"></div>
        <div class="table-container">
            <table border="1" width="100%">

                <tbody>
                <tr>
                    <th colspan="2" width="24%">Размеры</th>
                    <th rowspan="2" width="12%">Масса 1м, кг</th>
                    <th rowspan="2" width="12%">Метров в тонне</th>
                    <th rowspan="46" width="4%"></th>
                    <th colspan="2" width="24%">Размеры</th>
                    <th rowspan="2" width="12%">Масса 1м, кг</th>
                    <th rowspan="2" width="12%">Метров в тонне</th>
                </tr>
                <tr>

                    <th width="12%">b</th>
                    <th width="12%">t</th>
                    <th width="12%">b</th>
                    <th width="12%">t</th>
                </tr>

                <tr>
                    <td>
                        20
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        0,89
                    </td>
                    <td>
                        1123,6
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        10,79
                    </td>
                    <td>
                        92,68
                    </td>
                </tr>
                <tr>
                    <td>
                        20
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        1,15
                    </td>
                    <td>
                        869,57
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        12,25
                    </td>
                    <td>
                        81,63
                    </td>
                </tr>
                <tr>
                    <td>
                        25
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,12
                    </td>
                    <td>
                        892,86
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        15,1
                    </td>
                    <td>
                        66,23
                    </td>
                </tr>
                <tr>
                    <td>
                        25
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        1,46
                    </td>
                    <td>
                        684,93
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        17,9
                    </td>
                    <td>
                        55,87
                    </td>
                </tr>
                <tr>
                    <td>
                        28
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,27
                    </td>
                    <td>
                        787,4
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        14
                    </td>
                    <td>
                        20,63
                    </td>
                    <td>
                        48,47
                    </td>
                </tr>
                <tr>
                    <td>
                        30
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,36
                    </td>
                    <td>
                        735,29
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        16
                    </td>
                    <td>
                        23,3
                    </td>
                    <td>
                        42,92
                    </td>
                </tr>
                <tr>
                    <td>
                        30
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        1,78
                    </td>
                    <td>
                        561,8
                    </td>
                    <td>
                        110
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        11,89
                    </td>
                    <td>
                        84,1
                    </td>
                </tr>
                <tr>
                    <td>
                        32
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,46
                    </td>
                    <td>
                        684,93
                    </td>
                    <td>
                        110
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        13,5
                    </td>
                    <td>
                        74,07
                    </td>
                </tr>
                <tr>
                    <td>
                        32
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        1,91
                    </td>
                    <td>
                        523,56
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        15,46
                    </td>
                    <td>
                        64,68
                    </td>
                </tr>
                <tr>
                    <td>
                        35
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,6
                    </td>
                    <td>
                        625
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        9
                    </td>
                    <td>
                        17,3
                    </td>
                    <td>
                        57,8
                    </td>
                </tr>
                <tr>
                    <td>
                        35
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        2,1
                    </td>
                    <td>
                        476,19
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        19,1
                    </td>
                    <td>
                        52,36
                    </td>
                </tr>
                <tr>
                    <td>
                        35
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        2,58
                    </td>
                    <td>
                        387,6
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        22,68
                    </td>
                    <td>
                        44,09
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,85
                    </td>
                    <td>
                        540,54
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        14
                    </td>
                    <td>
                        26,2
                    </td>
                    <td>
                        38,17
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        2,42
                    </td>
                    <td>
                        413,22
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        16
                    </td>
                    <td>
                        29,65
                    </td>
                    <td>
                        33,73
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        2,98
                    </td>
                    <td>
                        335,57
                    </td>
                    <td>
                        140
                    </td>
                    <td>
                        9
                    </td>
                    <td>
                        19,41
                    </td>
                    <td>
                        51,52
                    </td>
                </tr>
                <tr>
                    <td>
                        45
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        2,08
                    </td>
                    <td>
                        480,77
                    </td>
                    <td>
                        140
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        21,45
                    </td>
                    <td>
                        46,62
                    </td>
                </tr>
                <tr>
                    <td>
                        45
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        2,73
                    </td>
                    <td>
                        366,3
                    </td>
                    <td>
                        140
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        25,5
                    </td>
                    <td>
                        39,22
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        3,05
                    </td>
                    <td>
                        327,87
                    </td>
                    <td>
                        160
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        24,67
                    </td>
                    <td>
                        40,54
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        3,77
                    </td>
                    <td>
                        265,25
                    </td>
                    <td>
                        160
                    </td>
                    <td>
                        11
                    </td>
                    <td>
                        27,02
                    </td>
                    <td>
                        37,01
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        4,47
                    </td>
                    <td>
                        223,71
                    </td>
                    <td>
                        160
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        29,35
                    </td>
                    <td>
                        34,07
                    </td>
                </tr>
                <tr>
                    <td>
                        56
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        3,44
                    </td>
                    <td>
                        290,7
                    </td>
                    <td>
                        160
                    </td>
                    <td>
                        14
                    </td>
                    <td>
                        34,2
                    </td>
                    <td>
                        29,24
                    </td>
                </tr>
                <tr>
                    <td>
                        56
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        4,25
                    </td>
                    <td>
                        235,29
                    </td>
                    <td>
                        160
                    </td>
                    <td>
                        16
                    </td>
                    <td>
                        38,52
                    </td>
                    <td>
                        25,96
                    </td>
                </tr>
                <tr>
                    <td>
                        63
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        3,9
                    </td>
                    <td>
                        256,41
                    </td>
                    <td>
                        160
                    </td>
                    <td>
                        18
                    </td>
                    <td>
                        43,01
                    </td>
                    <td>
                        23,25
                    </td>
                </tr>
                <tr>
                    <td>
                        63
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        4,81
                    </td>
                    <td>
                        207,9
                    </td>
                    <td>
                        160
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        47,41
                    </td>
                    <td>
                        21,09
                    </td>
                </tr>
                <tr>
                    <td>
                        63
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        5,72
                    </td>
                    <td>
                        174,83
                    </td>
                    <td>
                        180
                    </td>
                    <td>
                        11
                    </td>
                    <td>
                        30,47
                    </td>
                    <td>
                        32,82
                    </td>
                </tr>
                <tr>
                    <td>
                        70
                    </td>
                    <td>
                        4,5
                    </td>
                    <td>
                        4,87
                    </td>
                    <td>
                        205,34
                    </td>
                    <td>
                        180
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        33,12
                    </td>
                    <td>
                        30,19
                    </td>
                </tr>
                <tr>
                    <td>
                        70
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        5,38
                    </td>
                    <td>
                        185,87
                    </td>
                    <td>
                        200
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        36,97
                    </td>
                    <td>
                        27,05
                    </td>
                </tr>
                <tr>
                    <td>
                        70
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        6,39
                    </td>
                    <td>
                        156,49
                    </td>
                    <td>
                        200
                    </td>
                    <td>
                        13
                    </td>
                    <td>
                        39,92
                    </td>
                    <td>
                        25,05
                    </td>
                </tr>
                <tr>
                    <td>
                        70
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        7,39
                    </td>
                    <td>
                        135,32
                    </td>
                    <td>
                        200
                    </td>
                    <td>
                        14
                    </td>
                    <td>
                        42,8
                    </td>
                    <td>
                        23,36
                    </td>
                </tr>
                <tr>
                    <td>
                        70
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        8,37
                    </td>
                    <td>
                        119,47
                    </td>
                    <td>
                        200
                    </td>
                    <td>
                        16
                    </td>
                    <td>
                        48,65
                    </td>
                    <td>
                        20,55
                    </td>
                </tr>
                <tr>
                    <td>
                        75
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        5,8
                    </td>
                    <td>
                        172,41
                    </td>
                    <td>
                        200
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        60,08
                    </td>
                    <td>
                        16,64
                    </td>
                </tr>
                <tr>
                    <td>
                        75
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        6,89
                    </td>
                    <td>
                        145,14
                    </td>
                    <td>
                        200
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        74,02
                    </td>
                    <td>
                        13,51
                    </td>
                </tr>
                <tr>
                    <td>
                        75
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        7,96
                    </td>
                    <td>
                        125,63
                    </td>
                    <td>
                        200
                    </td>
                    <td>
                        30
                    </td>
                    <td>
                        87,56
                    </td>
                    <td>
                        11,42
                    </td>
                </tr>
                <tr>
                    <td>
                        75
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        9,02
                    </td>
                    <td>
                        110,86
                    </td>
                    <td>
                        220
                    </td>
                    <td>
                        14
                    </td>
                    <td>
                        47,4
                    </td>
                    <td>
                        21,1
                    </td>
                </tr>
                <tr>
                    <td>
                        75
                    </td>
                    <td>
                        9
                    </td>
                    <td>
                        10,7
                    </td>
                    <td>
                        93,46
                    </td>
                    <td>
                        220
                    </td>
                    <td>
                        16
                    </td>
                    <td>
                        53,83
                    </td>
                    <td>
                        18,58
                    </td>
                </tr>
                <tr>
                    <td>
                        80
                    </td>
                    <td>
                        5,5
                    </td>
                    <td>
                        6,78
                    </td>
                    <td>
                        147,49
                    </td>
                    <td>
                        250
                    </td>
                    <td>
                        16
                    </td>
                    <td>
                        61,55
                    </td>
                    <td>
                        16,25
                    </td>
                </tr>
                <tr>
                    <td>
                        80
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        7,36
                    </td>
                    <td>
                        135,87
                    </td>
                    <td>
                        250
                    </td>
                    <td>
                        18
                    </td>
                    <td>
                        68,86
                    </td>
                    <td>
                        14,52
                    </td>
                </tr>
                <tr>
                    <td>
                        80
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        8,51
                    </td>
                    <td>
                        117,51
                    </td>
                    <td>
                        250
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        76,11
                    </td>
                    <td>
                        13,14
                    </td>
                </tr>
                <tr>
                    <td>
                        80
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        9,65
                    </td>
                    <td>
                        103,63
                    </td>
                    <td>
                        250
                    </td>
                    <td>
                        22
                    </td>
                    <td>
                        83,31
                    </td>
                    <td>
                        12
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        8,33
                    </td>
                    <td>
                        120,05
                    </td>
                    <td>
                        250
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        93,97
                    </td>
                    <td>
                        10,64
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        9,64
                    </td>
                    <td>
                        103,73
                    </td>
                    <td>
                        250
                    </td>
                    <td>
                        28
                    </td>
                    <td>
                        104,5
                    </td>
                    <td>
                        9,57
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        10,93
                    </td>
                    <td>
                        91,49
                    </td>
                    <td>
                        250
                    </td>
                    <td>
                        30
                    </td>
                    <td>
                        111,44
                    </td>
                    <td>
                        8,97
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        9
                    </td>
                    <td>
                        12,2
                    </td>
                    <td>
                        81,97
                    </td>
                    <td>
                        250
                    </td>
                    <td>
                        35
                    </td>
                    <td>
                        128,51
                    </td>
                    <td>
                        7,78
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        6,5
                    </td>
                    <td>
                        10,06
                    </td>
                    <td>
                        99,4
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div><br>


    <h2>Вес уголка стального горячекатанного неравнополочного по ГОСТ 19772-93</h2>
    <div class="table-container-outer">
        <div class="table-container-fade"></div>
        <div class="table-container">
            <table border="1" width="100%">

                <tbody>
                <tr>
                    <th colspan="3" width="60%">Размеры</th>
                    <th rowspan="2" width="20%">Масса 1м, кг</th>
                    <th rowspan="2" width="20%">Метров в тонне</th>
                </tr>
                <tr>

                    <th width="20%">a</th>
                    <th width="20%">b</th>
                    <th width="20%">s</th>
                </tr>
                <tr>
                    <td>
                        25
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        1,5
                    </td>
                    <td>
                        0,5
                    </td>
                    <td>
                        2000
                    </td>
                </tr>
                <tr>
                    <td>
                        25
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        0,65
                    </td>
                    <td>
                        1538,5
                    </td>
                </tr>
                <tr>
                    <td>
                        32
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        1,5
                    </td>
                    <td>
                        0,64
                    </td>
                    <td>
                        1562,5
                    </td>
                </tr>
                <tr>
                    <td>
                        32
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        2,5
                    </td>
                    <td>
                        1,03
                    </td>
                    <td>
                        970,9
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        1,5
                    </td>
                    <td>
                        0,73
                    </td>
                    <td>
                        1369,9
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        0,96
                    </td>
                    <td>
                        1041,7
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,19
                    </td>
                    <td>
                        840,3
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        32
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        1,07
                    </td>
                    <td>
                        934,6
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        32
                    </td>
                    <td>
                        2,5
                    </td>
                    <td>
                        1,33
                    </td>
                    <td>
                        751,9
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        32
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,57
                    </td>
                    <td>
                        636,9
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        35
                    </td>
                    <td>
                        3,2
                    </td>
                    <td>
                        1,98
                    </td>
                    <td>
                        505,1
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        36
                    </td>
                    <td>
                        2,5
                    </td>
                    <td>
                        1,6
                    </td>
                    <td>
                        625
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        36
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,9
                    </td>
                    <td>
                        526,3
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        36
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        2,47
                    </td>
                    <td>
                        404,9
                    </td>
                </tr>
                <tr>
                    <td>
                        60
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        2,23
                    </td>
                    <td>
                        448,4
                    </td>
                </tr>
                <tr>
                    <td>
                        70
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        2,7
                    </td>
                    <td>
                        370,4
                    </td>
                </tr>
                <tr>
                    <td>
                        70
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        3,53
                    </td>
                    <td>
                        283,3
                    </td>
                </tr>
                <tr>
                    <td>
                        80
                    </td>
                    <td>
                        63
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        4,26
                    </td>
                    <td>
                        234,7
                    </td>
                </tr>
                <tr>
                    <td>
                        80
                    </td>
                    <td>
                        63
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        5,26
                    </td>
                    <td>
                        190,1
                    </td>
                </tr>
                <tr>
                    <td>
                        80
                    </td>
                    <td>
                        63
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        6,21
                    </td>
                    <td>
                        161
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        70
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        4,79
                    </td>
                    <td>
                        208,8
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        70
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        5,92
                    </td>
                    <td>
                        168,9
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        70
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        7,01
                    </td>
                    <td>
                        142,7
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        70
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        8,11
                    </td>
                    <td>
                        123,3
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        65
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        4,95
                    </td>
                    <td>
                        202
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        80
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        6,71
                    </td>
                    <td>
                        149
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        80
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        7,95
                    </td>
                    <td>
                        125,8
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        80
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        9,21
                    </td>
                    <td>
                        108,6
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        80
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        10,37
                    </td>
                    <td>
                        96,4
                    </td>
                </tr>
                <tr>
                    <td>
                        105
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        4,69
                    </td>
                    <td>
                        213,2
                    </td>
                </tr>
                <tr>
                    <td>
                        115
                    </td>
                    <td>
                        65
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        6,71
                    </td>
                    <td>
                        149
                    </td>
                </tr>
                <tr>
                    <td>
                        120
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        9,84
                    </td>
                    <td>
                        101,6
                    </td>
                </tr>
                <tr>
                    <td>
                        120
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        11,41
                    </td>
                    <td>
                        87,6
                    </td>
                </tr>
                <tr>
                    <td>
                        120
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        12,88
                    </td>
                    <td>
                        77,6
                    </td>
                </tr>
                <tr>
                    <td>
                        160
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        14,98
                    </td>
                    <td>
                        66,8
                    </td>
                </tr>
                <tr>
                    <td>
                        160
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        93,97
                    </td>
                    <td>
                        10,64
                    </td>
                </tr>
                <tr>
                    <td>
                        180
                    </td>
                    <td>
                        140
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        14,55
                    </td>
                    <td>
                        68,7
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div><br>
    <div class="table-container-outer">
        <div class="table-container-fade"></div>
        <div class="table-container">
            <table>

            </table>
        </div>
    </div><h2>Вес уголка стального горячекатанного неравнополочного по ГОСТ8510-86</h2>
    <div class="table-container-outer">
        <div class="table-container-fade"></div>
        <div class="table-container">
            <table border="1" width="100%">

                <tbody>
                <tr>
                    <th colspan="3" width="60%">Размеры</th>
                    <th rowspan="2" width="20%">Масса 1м, кг</th>
                    <th rowspan="2" width="20%">Метров в тонне</th>
                </tr>
                <tr>

                    <th width="20%">a</th>
                    <th width="20%">b</th>
                    <th width="20%">s</th>
                </tr>
                <tr>
                    <td>
                        25
                    </td>
                    <td>
                        16
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        0,91
                    </td>
                    <td>
                        1098,9
                    </td>
                </tr>
                <tr>
                    <td>
                        32
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,17
                    </td>
                    <td>
                        854,7
                    </td>
                </tr>
                <tr>
                    <td>
                        32
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        1,52
                    </td>
                    <td>
                        657,9
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,48
                    </td>
                    <td>
                        675,7
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        1,94
                    </td>
                    <td>
                        515,5
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        2,37
                    </td>
                    <td>
                        421,9
                    </td>
                </tr>
                <tr>
                    <td>
                        45
                    </td>
                    <td>
                        28
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,68
                    </td>
                    <td>
                        595,2
                    </td>
                </tr>
                <tr>
                    <td>
                        45
                    </td>
                    <td>
                        28
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        2,2
                    </td>
                    <td>
                        454,5
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        32
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        1,9
                    </td>
                    <td>
                        526,3
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        32
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        2,4
                    </td>
                    <td>
                        416,7
                    </td>
                </tr>
                <tr>
                    <td>
                        56
                    </td>
                    <td>
                        36
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        2,81
                    </td>
                    <td>
                        355,9
                    </td>
                </tr>
                <tr>
                    <td>
                        56
                    </td>
                    <td>
                        36
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        3,46
                    </td>
                    <td>
                        289
                    </td>
                </tr>
                <tr>
                    <td>
                        63
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        3,17
                    </td>
                    <td>
                        315,5
                    </td>
                </tr>
                <tr>
                    <td>
                        63
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        3,91
                    </td>
                    <td>
                        255,8
                    </td>
                </tr>
                <tr>
                    <td>
                        63
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        4,63
                    </td>
                    <td>
                        216
                    </td>
                </tr>
                <tr>
                    <td>
                        63
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        6,03
                    </td>
                    <td>
                        165,8
                    </td>
                </tr>
                <tr>
                    <td>
                        70
                    </td>
                    <td>
                        45
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        4,39
                    </td>
                    <td>
                        227,8
                    </td>
                </tr>
                <tr>
                    <td>
                        75
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        4,79
                    </td>
                    <td>
                        208,8
                    </td>
                </tr>
                <tr>
                    <td>
                        75
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        5,69
                    </td>
                    <td>
                        175,7
                    </td>
                </tr>
                <tr>
                    <td>
                        75
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        7,43
                    </td>
                    <td>
                        134,6
                    </td>
                </tr>
                <tr>
                    <td>
                        80
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        4,49
                    </td>
                    <td>
                        222,7
                    </td>
                </tr>
                <tr>
                    <td>
                        80
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        5,92
                    </td>
                    <td>
                        168,9
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        56
                    </td>
                    <td>
                        5,5
                    </td>
                    <td>
                        6,17
                    </td>
                    <td>
                        162,1
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        56
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        6,7
                    </td>
                    <td>
                        149,3
                    </td>
                </tr>
                <tr>
                    <td>
                        90
                    </td>
                    <td>
                        56
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        8,77
                    </td>
                    <td>
                        114
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        63
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        7,53
                    </td>
                    <td>
                        132,8
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        63
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        8,7
                    </td>
                    <td>
                        114,9
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        63
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        9,87
                    </td>
                    <td>
                        101,3
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        63
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        12,14
                    </td>
                    <td>
                        82,4
                    </td>
                </tr>
                <tr>
                    <td>
                        110
                    </td>
                    <td>
                        70
                    </td>
                    <td>
                        6,5
                    </td>
                    <td>
                        8,98
                    </td>
                    <td>
                        111,4
                    </td>
                </tr>
                <tr>
                    <td>
                        110
                    </td>
                    <td>
                        70
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        10,93
                    </td>
                    <td>
                        91,5
                    </td>
                </tr>
                <tr>
                    <td>
                        125
                    </td>
                    <td>
                        80
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        11
                    </td>
                    <td>
                        101,6
                    </td>
                </tr>
                <tr>
                    <td>
                        120
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        7
                    </td>
                    <td>
                        11,04
                    </td>
                    <td>
                        90,6
                    </td>
                </tr>
                <tr>
                    <td>
                        125
                    </td>
                    <td>
                        80
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        12,58
                    </td>
                    <td>
                        79,5
                    </td>
                </tr>
                <tr>
                    <td>
                        125
                    </td>
                    <td>
                        80
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        15,47
                    </td>
                    <td>
                        64,6
                    </td>
                </tr>
                <tr>
                    <td>
                        125
                    </td>
                    <td>
                        80
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        18,34
                    </td>
                    <td>
                        54,5
                    </td>
                </tr>
                <tr>
                    <td>
                        140
                    </td>
                    <td>
                        90
                    </td>
                    <td>
                        8
                    </td>
                    <td>
                        14,13
                    </td>
                    <td>
                        70,8
                    </td>
                </tr>
                <tr>
                    <td>
                        140
                    </td>
                    <td>
                        90
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        17,46
                    </td>
                    <td>
                        57,3
                    </td>
                </tr>
                <tr>
                    <td>
                        160
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        9
                    </td>
                    <td>
                        17,96
                    </td>
                    <td>
                        55,7
                    </td>
                </tr>
                <tr>
                    <td>
                        160
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        19,85
                    </td>
                    <td>
                        50,4
                    </td>
                </tr>
                <tr>
                    <td>
                        160
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        23,58
                    </td>
                    <td>
                        42,4
                    </td>
                </tr>
                <tr>
                    <td>
                        160
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        14
                    </td>
                    <td>
                        27,26
                    </td>
                    <td>
                        36,7
                    </td>
                </tr>
                <tr>
                    <td>
                        180
                    </td>
                    <td>
                        110
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        22,2
                    </td>
                    <td>
                        45
                    </td>
                </tr>
                <tr>
                    <td>
                        180
                    </td>
                    <td>
                        110
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        26,04
                    </td>
                    <td>
                        37,9
                    </td>
                </tr>
                <tr>
                    <td>
                        200
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        11
                    </td>
                    <td>
                        27,37
                    </td>
                    <td>
                        36,5
                    </td>
                </tr>
                <tr>
                    <td>
                        200
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        29,74
                    </td>
                    <td>
                        33,6
                    </td>
                </tr>
                <tr>
                    <td>
                        200
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        14
                    </td>
                    <td>
                        34,43
                    </td>
                    <td>
                        29
                    </td>
                </tr>
                <tr>
                    <td>
                        200
                    </td>
                    <td>
                        125
                    </td>
                    <td>
                        16
                    </td>
                    <td>
                        39,07
                    </td>
                    <td>
                        25,6
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div><br>

    <h2>Алюминиевый уголок</h2>

    <p align="justify">В промышленной сфере деятельности алюминий просто не заменим из-за его специфических свойств.
        Этот металл обладает очень маленькой удельной массой по сравнению с другими. Он вязкий и довольно прочный, но в
        чистом виде алюминий не используется в промышленности, в основном используется его сплав АД31. Хотя, чаще всего
        сплавы подбираются под конкретную конструкцию.</p>
    <p align="justify">Алюминиевый уголок имеет очень широкий спектр применения. Его используют не только в
        промышленности, но и в быту (ремонты, реставрации, декорации). Такая обширная сфера применения обусловлена тем,
        что алюминиевый уголок имеет очень маленький вес при большом запасе прочности. Он выступает как крепежный
        материал, элемент в несущих и поддерживающих фермах, стыковочно-фиксирующий элемент при ремонте. Так же алюминий
        применяется для изготовления каркасных изделий, главной характеристикой которых, должен быть максимально
        сниженный вес.</p>
    <p align="justify">Благодаря малому весу и простате в обработке алюминий очень востребован при постройке товарных
        лотков, полок, стеллажей. Изделия из этого материала годами сохраняют свой первоначальный вид и очень легки в
        демонтаже и транспортировке. В промышленности используют ещё одно свойство алюминия – высокую
        тепло-проводимость. Из уголка с алюминия часто делают радиаторные ребра, чтобы снизить температуру рабочего
        объекта. </p>
    <p align="justify">Многие при виде разницы в цене алюминиевого уголка и уголков с других металлов очень часто
        забывают об эксплуатационных свойствах этих металлов. Алюминий почти не подвержен окислению и прекрасно
        поддается окраске любыми видами лакокрасочных материалов при этом, не теряя своих свойств и первоначальный
        вид. </p>
    <p align="justify">Так же алюминиевый уголок часто используют для изготовления несущих ферм, которые обеспечивают
        снижение давления на опорные конструкции без потерь прочности поддерживаемого элемента объекта. Алюминиевый
        уголок также незаменим при изготовлении легких наружных и внутренних каркасов. Благодаря физико-химическим
        свойствам этого металла такие каркасы практически не окисляются и легко красятся. Этот металл часто используют
        для изготовления оконных рам и рекламных стендов. Алюминиевый уголок пользуется большим спросом у производителей
        мебели, которые применяют его в изготовлении и декорации надежной корпусной мебели.</p>
    <p align="justify">Незначительный вес алюминиевого уголка по сравнению с другими металлами позволяют облегчить
        погрузку и транспортировку конструкций из него, что является дополнительным преимуществом этого материала.</p>

    <h2>Вес уголка алюминиевого</h2>
    <div class="table-container-outer">
        <div class="table-container-fade"></div>
        <div class="table-container">
            <table width="100%">
                <tbody>
                <tr>
                    <th style="color: rgb(0, 0, 0);">
                        Размер 1
                    </th>
                    <th style="color: rgb(0, 0, 0);">
                        Размер 2
                    </th>
                    <th style="color: rgb(0, 0, 0);">
                        Размер 3
                    </th>
                    <th style="color: rgb(0, 0, 0);" rowspan="2">
                        сплав
                    </th>
                    <th style="color: rgb(0, 0, 0);" rowspan="2">
                        вес.м/пог
                    </th>
                </tr>
                <tr>
                    <td>
                        a
                    </td>
                    <td>
                        b
                    </td>
                    <td>
                        s
                    </td>
                </tr>
                <tr>
                    <td>
                        10
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        1,2
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>
                        0,06
                    </td>
                </tr>
                <tr>
                    <td>
                        12
                    </td>
                    <td>
                        12
                    </td>
                    <td>
                        1,5
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>
                        0,091
                    </td>
                </tr>
                <tr>
                    <td>
                        15
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>
                        0,124
                    </td>
                </tr>
                <tr>
                    <td>
                        15
                    </td>
                    <td>
                        15
                    </td>
                    <td>
                        1
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        0,079
                    </td>
                </tr>
                <tr>
                    <td>
                        15
                    </td>
                    <td>
                        15
                    </td>
                    <td>
                        1,5
                    </td>
                    <td>
                        АД0, АД31, АД31Т, АД31Т1
                    </td>
                    <td>
                        0,116
                    </td>
                </tr>
                <tr>
                    <td>
                        15
                    </td>
                    <td>
                        15
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        0,151
                    </td>
                </tr>
                <tr>
                    <td>
                        20
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        1,5
                    </td>
                    <td>
                        АД31Т1
                    </td>
                    <td>
                        0,156
                    </td>
                </tr>
                <tr>
                    <td>
                        20
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        0,205
                    </td>
                </tr>
                <tr>
                    <td>
                        20
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>
                        0,301
                    </td>
                </tr>
                <tr>
                    <td>
                        20
                    </td>
                    <td>
                        60
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД31Т1
                    </td>
                    <td>

                    </td>
                </tr>
                <tr>
                    <td>
                        25
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        1,2
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>

                    </td>
                </tr>
                <tr>
                    <td>
                        25
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        1,5
                    </td>
                    <td>
                        АД31Т1
                    </td>
                    <td>
                        0,196
                    </td>
                </tr>
                <tr>
                    <td>
                        25
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД0, АД31, АД31Т, АД31Т1
                    </td>
                    <td>
                        0,259
                    </td>
                </tr>
                <tr>
                    <td>
                        30
                    </td>
                    <td>
                        30
                    </td>
                    <td>
                        1,2
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>

                    </td>
                </tr>
                <tr>
                    <td>
                        30
                    </td>
                    <td>
                        30
                    </td>
                    <td>
                        1,5
                    </td>
                    <td>
                        АД31Т1
                    </td>
                    <td>
                        0,237
                    </td>
                </tr>
                <tr>
                    <td>
                        30
                    </td>
                    <td>
                        30
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД0, АД31, АД31Т, АД31Т1
                    </td>
                    <td>
                        0,313
                    </td>
                </tr>
                <tr>
                    <td>
                        30
                    </td>
                    <td>
                        30
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        0,462
                    </td>
                </tr>
                <tr>
                    <td>
                        30
                    </td>
                    <td>
                        15
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>
                        0,233
                    </td>
                </tr>
                <tr>
                    <td>
                        30
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>
                        0,26
                    </td>
                </tr>
                <tr>
                    <td>
                        35
                    </td>
                    <td>
                        35
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        0,369
                    </td>
                </tr>
                <tr>
                    <td>
                        35
                    </td>
                    <td>
                        35
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        АД0, АД31, АД31Т, АД31Т1
                    </td>
                    <td>
                        0,545
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        1,8
                    </td>
                    <td>
                        АД31Т1
                    </td>
                    <td>

                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        0,421
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        2,5
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        0,525
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        0,626
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        АД0, АД31, АД31Т, 6082Т6
                    </td>
                    <td>
                        0,824
                    </td>
                </tr>
                <tr>
                    <td>
                        40
                    </td>
                    <td>
                        20
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        0,313
                    </td>
                </tr>
                <tr>
                    <td>
                        45
                    </td>
                    <td>
                        45
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        0,932
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД0, АД31, АД31Т, АД31Т1
                    </td>
                    <td>
                        0,529
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        2,5
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>

                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        АД0, АД31, АД31Т, 6082Т6
                    </td>
                    <td>
                        0,786
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        АД0, АД31, АД31Т, 6082Т6
                    </td>
                    <td>
                        1,041
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        АД0, АД31, АД31Т, Д16Т
                    </td>
                    <td>
                        1,287
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        25
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>
                        0,585
                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        30
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>

                    </td>
                </tr>
                <tr>
                    <td>
                        50
                    </td>
                    <td>
                        30
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>

                    </td>
                </tr>
                <tr>
                    <td>
                        60
                    </td>
                    <td>
                        60
                    </td>
                    <td>
                        6
                    </td>
                    <td>
                        АД0, АД31, АД31Т
                    </td>
                    <td>
                        1,854
                    </td>
                </tr>
                <tr>
                    <td>
                        60
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        2
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>

                    </td>
                </tr>
                <tr>
                    <td>
                        60
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        4
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>
                        1,037
                    </td>
                </tr>
                <tr>
                    <td>
                        80
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        АД31
                    </td>
                    <td>
                        0,951
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        100
                    </td>
                    <td>
                        10
                    </td>
                    <td>
                        АД31Т1
                    </td>
                    <td>
                        5,149
                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        40
                    </td>
                    <td>
                        3
                    </td>
                    <td>
                        АД31Т1
                    </td>
                    <td>

                    </td>
                </tr>
                <tr>
                    <td>
                        100
                    </td>
                    <td>
                        50
                    </td>
                    <td>
                        5
                    </td>
                    <td>
                        АД31Т1
                    </td>
                    <td>
                        1,956
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <p align="justify">Проконсультироваться по видам уголка и узнать условия поставки вы можете по телефону у наших
        менеджеров. </p>

@stop